### ISSUE TITLE
Creation of codons file for MNPs script

### ISSUE THREAD

**Issue by sbgLuka** [Sentieon/sentieon-scripts#1]
Hi, 

Thank you for providing the code for merging MNPs. I wanted to create codons file myself, however I am missing some steps. I am missing the step for creation of: GRCh38_ucsc_refseq_good_transcripts.noALT.bed which is required for awk script. Could you provide steps how to create it, if I want to use different reference than GRCh38? 

Thanks,
Luka.

**Comment by DonFreed** [comment]
Hi Luka,

Thank you for your interest in our project and for bringing this issue to our attention. We've added some additional directions to the [merge_mnp/README](https://github.com/Sentieon/sentieon-scripts/tree/master/merge_mnp#creating-a-codonstxt-file) file that should solve this issue. We've also updated the awk script so that it is compatible with the most recent output from the UCSC table browser. Please feel free to reopen (or comment on) this issue if you still have questions.

Best,
Don

**Comment by b-math** [comment]
Dear development team,

could it be that you gave the wrong script name in the [merge_mnp/README](https://github.com/Sentieon/sentieon-scripts/blob/master/merge_mnp/README.md)?

In the README it says 
cat <BED> | awk -f **mnp_with_codons-create_codon_file.awk** > codons.txt

however, I can only find [**merge_by_codon-preprocess_codon_file.awk**](https://github.com/Sentieon/sentieon-scripts/blob/master/merge_mnp/merge_by_codon-preprocess_codon_file.awk) in your directory. However, using this file seems to lead to correct results when applying on the UCSC table output.

Best regards, Barbara
