### ISSUE TITLE
bwa index lack bwtsw algorithm

### ISSUE THREAD

**Issue by dozhun** [Sentieon/sentieon-scripts#9]
run based sentieon/202112.04
$sentieon bwa index

Usage:   bwa index [options] <in.fasta>

Options: -a STR    BWT construction algorithm: is or rb2 [auto]
         -p STR    prefix of the index [same as fasta name]
         -6        index files named as <in.fasta>.64.* instead of <in.fasta>.* 

Warning: `-a bwtsw' does not work for short genomes, while `-a is' and
         `-a div' do not work not for long genomes.

I can't find bwtsw algorithm in line start with Options

Further , if i run `bwa index -a bwtsw hg19.fa`, then back a error `[bwa_index] unknown algorithm: 'bwtsw'.`
Is Sendion not requiring the bwtsw algorithm or are there other considerations?

**Comment by DonFreed** [comment]
Sentieon's `bwa index` command does not support the `bwtsw` algorithm, so this is the expected behavior. You can use either the `is` or `rb2` algorithms or let the software choose which algorithm to use.

Happy to help you here, but please also feel free to email Sentieon's support team at support@sentieon.com for general support questions.
